function [input_data target_value] = create_network_input_and_target_data( ...
        data,...
        speed,...
        angle_of_movement,...
        distance_to_source,...
        diff_angle_of_movement,...
        avg_speed_from_beginning,...
        avg_speed_w,...
        var_angle_w,...
        var_angle_from_beginning,...
        angles_toward_centroids,...
        distance_toward_centroids,...
        angles_toward_center_of_mass,...
        distance_toward_center_of_mass,...
        global_mean_speed,...
        distance_from_nearest_agent,...
        distance_to_building ...
        )
    input_data = [];
    target_value = [];

    for i=1:size(data,2)/2,
       input_data = [ input_data; 
           speed(:,i) ...
           angle_of_movement(:,i) ... 
           distance_to_source(:,i) ...
           diff_angle_of_movement(:,i) ...
           avg_speed_from_beginning(:,i) ...
           avg_speed_w(:,i) ...
           var_angle_w(:,i) ...
           var_angle_from_beginning(:,i)  ...
           angles_toward_centroids(:,(i*k)-((k)-1):i*k) ...
           distance_toward_centroids(:,(i*k)-((k)-1):i*k) ...
           angles_toward_center_of_mass(:,i) ...
           distance_toward_center_of_mass(:,i) ...
           global_mean_speed(:,:) ...
           distance_from_nearest_agent(:,i) ...
           distance_to_building(:,(i*4)-3:i*4) ...
       ];
       target_value = [ target_value; speed(:,i) angle_of_movement(:,i)];
    end

    % Replace NaNs with 0s
    input_data(isnan(input_data))=0;
    target_value(isnan(target_value))=0;
end