function [ err ] = ga_func( k, pca_n, w)
    
    [ input_data target_value ] = create_network_input_and_target_data(...
        data,...
        speed,...
        angle_of_movement,...
        distance_to_source,...
        diff_angle_of_movement,...
        avg_speed_from_beginning,...
        avg_speed_w,...
        var_angle_w,...
        var_angle_from_beginning,...
        angles_toward_centroids,...
        distance_toward_centroids,...
        angles_toward_center_of_mass,...
        distance_toward_center_of_mass,...
        global_mean_speed,...
        distance_from_nearest_agent,...
        distance_to_building ...
    );

end

