function [ err ] = ga_func( k, pca_n, w)

    global features
    
    % w-dependent features
    features('avg_speed_w') = create_avg_speed_w(data,speed,w);
    features('var_angle_w') = create_var_angle_w(data,angle_of_movement,w);
    
    % k-dependent features
    features('centroids') = create_centroids(data,k)
    [ angles_toward_centroids distance_toward_centroids ] = create_angles_and_distances_toward_centroids(data, centroids);
    features('angles_toward_centroids') = angles_toward_centroids;
    features('distance_toward_centroids') = distance_toward_centroids;
    
    [ input_data target_value ] = create_network_input_and_target_data(...
        data,...
        features('speed'),...
        features('angle_of_movement'),...
        features('distance_to_source'),...
        features('diff_angle_of_movement'),...
        features('avg_speed_from_beginning'),...
        features('avg_speed_w'),...
        features('var_angle_w'),...
        features('var_angle_from_beginning'),...
        features('angles_toward_centroids'),...
        features('distance_toward_centroids'),...
        features('angles_toward_center_of_mass'),...
        features('distance_toward_center_of_mass'),...
        features('global_mean_speed'),...
        features('distance_from_nearest_agent'),...
        features('distance_to_building') ...
    );
end

